config/routes.rb
#TODO write tests for routes (check where you can get without authentication)
Rails.application.routes.draw do
  resources :users, only: [:index]
  resources :user_hobbies, only: [:index, :new, :create]
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  resources :hobbies, only: [:index, :new, :create]
  root to: 'users#show'
  get 'users/:id/nearby', to: 'users#nearby', as: 'users_nearby'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hobby.rb
class Hobby < ApplicationRecord
  has_many :user_hobbies
  has_many :users, through: :user_hobbies
  validates :name, presence: true, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_hobbies
  has_many :hobbies, through: :user_hobbies

  devise :database_authenticatable, :registerable,
         :rememberable, :validatable

  validates :username, presence: true

  geocoded_by :ip_address
  after_validation :geocode

end

app/models/user_hobby.rb
class UserHobby < ApplicationRecord
  validates :hobby_id, :uniqueness => { :scope => [:user_id] }
  belongs_to :user
  belongs_to :hobby
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end

  def user_ip
    request.remote_ip
  end

  def set_user_ip
    current_user.update(ip_address: user_ip)
  end
end

app/controllers/hobbies_controller.rb
class HobbiesController < ApplicationController
  before_action :authenticate_user!

  def index
    @hobbies = Hobby.all
    @user_hobby = UserHobby.new
  end

  def new
    @hobby = Hobby.new
    render 'new'
  end

  def create
    @hobby = Hobby.new(hobby_params)
    if @hobby.save
      redirect_to hobbies_url, notice: 'Hobby has been saved'
    else
      render 'new'
    end
  end

  private

  def hobby_params
    params.require(:hobby).permit(:name)
  end

end

app/controllers/user_hobbies_controller.rb
class UserHobbiesController < ApplicationController
  before_action :authenticate_user!

  def new
    @user_hobby = UserHobby.new
    render 'new'
  end

  def create
    @user_hobby = UserHobby.new(user_hobby_params)
    if @user_hobby.save
      redirect_to hobbies_url, notice: 'Hobby has been assigned'
    else
      redirect_to hobbies_url
    end
  end

  private

  def user_hobby_params
    params.require(:user_hobby).permit(:user_id, :hobby_id)
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  def create
    super
    set_user_ip
  end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = current_user
  end

  def nearby
    set_user_ip
    @users = current_user.nearbys(100000)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/user_hobbies_helper.rb
module UserHobbiesHelper
end

app/helpers/user_ip_controller_helper.rb
module UserIpControllerHelper
end

app/helpers/user_ip_helper.rb
module UserIpHelper
end

app/helpers/user_nearby_helper.rb
module UserNearbyHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/hobbies/_form.html.erb
<%= simple_form_for @hobby do |f| %>
  <%= f.input :name, label: 'Name' %>
  <br>
  <%= f.button :submit, class: 'btn btn-primary' %>
<% end %>

app/views/hobbies/edit.html.erb
<h1>Editing hobby</h1>

<%= render 'form' %>

<%= link_to 'Show', [@hobby.users, @hobby] %> |
<%= link_to 'Back', users_hobbies_path(@hobby.users) %>

app/views/hobbies/index.html.erb
<%= link_to 'Profile', root_path(id: current_user.id) %>
<br>
<h1>Hobbies</h1>
<style>
  table {
    border-collapse: collapse;
  }
  th, td {
    border: 1px solid #ccc;
    padding: 10px;
    text-align: left;
  }
</style>
<% if @hobbies.empty? %>
  There are no hobbies
  <br>
<% else %>
  <table>
  <tr>
    <th>Hobby</th>
    <th>Actions</th>
  </tr>
  <tr> No hobbies </tr>
    <% @hobbies.each do |hobby| %>
      <tr>
        <td>
          <%= hobby.name %>
        </td>
        <td>
          <%= simple_form_for @user_hobby do |f| %>
            <%= f.hidden_field :user_id, :value => current_user.id %>
            <%= f.hidden_field :hobby_id, :value => hobby.id %>
            <%= f.submit 'Assign', class: 'btn btn-primary' %>
          <% end %>
        </td>
      </tr>
    <% end %>
    <% end %>
</table>
<br>
<%= link_to 'Add New Hobby', new_hobby_path %>

app/views/hobbies/new.html.erb
<h1>New hobby</h1>

<%= render 'form' %>
<br>
<%= link_to 'Back', hobbies_path %>

app/views/hobbies/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_users_hobby_path(@hobby.users, @hobby) %> |
<%= link_to 'Back', users_hobbies_path(@hobby.users) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Untitled</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<%= link_to 'Profile', root_path %>
<br>
<h1>Users</h1>
<style>
  table {
    border-collapse: collapse;
  }
  th, td {
    border: 1px solid #ccc;
    padding: 10px;
    text-align: left;
  }
</style>
<table>
  <tr>
    <th>Username</th>
    <th>Hobbies</th>
  </tr>
  <% if @users.empty? %>
    <tr> No users </tr>
  <% else %>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %><br/></td>
        <td>
          <table>
            <%user.hobbies.each do |hobby|%>
              <td><%= "#{hobby.name} " %></td>
            <%end %>
          </table>

        </td>
      </tr>
    <% end %>
    <% end %>

</table>

app/views/users/nearby.erb
<%= link_to 'Profile', root_path %>
<style>
  table {
    border-collapse: collapse;
  }
  th, td {
    border: 1px solid #ccc;
    padding: 10px;
    text-align: left;
  }
</style>
<h1>Users nearby</h1>
<table>
  <% if @users.empty? %>
    <tr> No users nearby </tr>
  <% else %>
    <% @users.each do |user| %>
      <tr>
        <td>
          <%= user.username %>
        </td>
      </tr>
    <% end %>
  <% end %>
</table>
<br>

app/views/users/show.html.erb
<%= link_to 'Hobbies', hobbies_path %>
<%= link_to 'Users', users_path %>
<%= link_to 'Sign out', destroy_user_session_path, :method => :delete %>
<%= link_to 'Users nearby', users_nearby_path(current_user.id) %>
<%= link_to 'Edit profile', edit_user_registration_path %>

<br>
<h1><%= @user.username %></h1>
<h1>Hobbies</h1>
<style>
  table {
    border-collapse: collapse;
  }
  th, td {
    border: 1px solid #ccc;
    padding: 10px;
    text-align: left;
  }
</style>
<% if @user.hobbies.empty? %>
  You have no hobbies
  <% else %>
  <table>
    <% @user.hobbies.each do |hobby| %>
      <tr>
        <td>
          <%= hobby.name %>
        </td>
      </tr>
    <% end %>
  </table>
<% end %>
<br>